name: CI

on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest,windows-latest]
        haxe: [4.0.5]
      fail-fast: true
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: ${{ matrix.haxe }}
      - run: haxe -version
      - run: haxelib git format https://github.com/haxefoundation/format
      - run: haxelib git hscript https://github.com/HaxeFoundation/hscript
      - name: list dir
        run: ls
      - name: Run tests
        run: haxe test.hxml
