name: CI

on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest,windows-latest]
        haxe: [4.0.5]
      fail-fast: true
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: "Setup Node.js"
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      -uses: 
      - uses: krdlab/setup-haxe@v1
      - uses: ./
          haxe-version: ${{ matrix.haxe }}
      - run: haxe -version
      - run: haxelib git format https://github.com/haxefoundation/format
      - run: haxelib git hscript https://github.com/HaxeFoundation/hscript
      - run: haxelib install hxjava
      - run: haxelib install hxnodejs
      - run: haxelib install hxcs
      - run: haxelib install hxcpp
      - run: haxe test.hxml
      - run: haxe build.hxml
